version: '3.8'

services:
  api:
    build:
      context: ./clinic-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./clinic-api/.env.production
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/clinic-management
      # JWT_SECRET is now loaded from .env.production file
    depends_on:
      - mongodb
    volumes:
      - ./clinic-api:/app
      - /app/node_modules
    command: npm start
    networks:
      - clinic-network

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - clinic-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "'db.runCommand({ ping: 1 })'"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./clinic-web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    volumes:
      - ./clinic-web:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - clinic-network

networks:
  clinic-network:
    driver: bridge

volumes:
  mongodb_data:
